#!/bin/bash

#Centering Function
function print_centered {
     [[ $# == 0 ]] && return 1

     declare -i TERM_COLS="$(tput cols)"
     declare -i str_len="${#1}"
     [[ $str_len -ge $TERM_COLS ]] && {
          echo "$1";
          return 0;
     }

     declare -i filler_len="$(( (TERM_COLS - str_len) / 2 ))"
     [[ $# -ge 2 ]] && ch="${2:0:1}" || ch=" "
     filler=""
     for (( i = 0; i < filler_len; i++ )); do
          filler="${filler}${ch}"
     done

     printf "%s%s%s" "$filler" "$1" "$filler"
     [[ $(( (TERM_COLS - str_len) % 2 )) -ne 0 ]] && printf "%s" "${ch}"
     printf "\n"

     return 0
}

#cat ~/Ubuntu-Startup-Message/ascii/ubuntulogo
bash ~/new/ascii/image.sh
TEMP=$(date +%A)
#date +"%A %d %B"
print_centered $(date +%A)
#print_centered $(date +%m-%d-%Y)
print_centered $(date +%B-%d-%Y)


#Quote Generator
#Quotes can be changes by editing the text in ~/Ubuntu-Startup-Message/quotes
if [ $TEMP = 'Monday' ]; then
	cat ~/Ubuntu-Startup-Message/quotes/Monday
fi

if [ $TEMP = 'Tuesday' ]; then
        cat $(~/Ubuntu-Startup-Message/quotes/Tuesday)
fi
#echo value to a variable then print_centered the string

if [ $TEMP = 'Wednesday' ]; then
        cat ~/Ubuntu-Startup-Message/quotes/Wednesday
fi

if [ $TEMP = 'Thursday' ]; then
        cat ~/Ubuntu-Startup-Message/quotes/Thursday
fi

if [ $TEMP = 'Friday' ]; then
        cat ~/Ubuntu-Startup-Message/quotes/Friday
fi

if [ $TEMP = 'Saturday' ]; then
        cat ~/Ubuntu-Startup-Message/quotes/Saturday
fi

if [ $TEMP = 'Sunday' ]; then
        cat ~/Ubuntu-Startup-Message/quotes/Sunday
fi

#Checks if there is an update available. If there is no update avaiable, then it returns nothing to keep a clean look.
#if [ $(/usr/lib/update-notifier/apt-check 2>&1 | cut -d ';' -f 2) -ge 1 ]; then
#	echo "                                                Available updates: $(/usr/lib/update-notifier/apt-check 2>&1 | cut -d ';' -f 2)"
#fi
#
#if [ $(/usr/lib/update-notifier/apt-check 2>&1 | cut -d ';' -f 1) -ge 1 ]; then
#	echo"                                                 Security updates: $(/usr/lib/update-notifier/apt-check 2>&1 | cut -d ';' -f 1)"
#fi




function print_centered {
     [[ $# == 0 ]] && return 1

     declare -i TERM_COLS="$(tput cols)"
     declare -i str_len="${#1}"
     [[ $str_len -ge $TERM_COLS ]] && {
          echo "$1";
          return 0;
     }

     declare -i filler_len="$(( (TERM_COLS - str_len) / 2 ))"
     [[ $# -ge 2 ]] && ch="${2:0:1}" || ch=" "
     filler=""
     for (( i = 0; i < filler_len; i++ )); do
          filler="${filler}${ch}"
     done

     printf "%s%s%s" "$filler" "$1" "$filler"
     [[ $(( (TERM_COLS - str_len) % 2 )) -ne 0 ]] && printf "%s" "${ch}"
     printf "\n"

     return 0
}
